const books = [
  {
  id: 1,
  title: "Nom",
  image: "...",
  category: "science",
  available: true
},
  {
    id: 1,
    title: "Clean Code",
    author: "Robert C. Martin",
    status: "Disponible",
    image: "https://picsum.photos/200?1",
  },
  {
    id: 2,
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    status: "Indisponible",
    image: "https://picsum.photos/200?2",
  },
  {
    id: 3,
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    status: "Disponible",
    image: "https://picsum.photos/200?3",
  },
  {
    id: 4,
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    status: "Disponible",
    image: "https://picsum.photos/200?4",
  },
  {
    id: 5,
    title: "React Guide",
    author: "Dan Abramov",
    status: "Indisponible",
    image: "https://picsum.photos/200?5",
  },
  {
    id: 6,
    title: "HTML & CSS",
    author: "Jon Duckett",
    status: "Disponible",
    image: "https://picsum.photos/200?6",
  },
  {
    id: 7,
    title: "Node.js Basics",
    author: "Ryan Dahl",
    status: "Disponible",
    image: "https://picsum.photos/200?7",
  },
  {
    id: 8,
    title: "Python Crash Course",
    author: "Eric Matthes",
    status: "Disponible",
    image: "https://picsum.photos/200?8",
  },
  {
    id: 9,
    title: "PHP & MySQL",
    author: "Luke Welling",
    status: "Indisponible",
    image: "https://picsum.photos/200?9",
  },
  {
    id: 10,
    title: "Laravel Up & Running",
    author: "Matt Stauffer",
    status: "Disponible",
    image: "https://picsum.photos/200?10",
  },
  {
    id: 11,
    title: "Design Patterns",
    author: "Erich Gamma",
    status: "Disponible",
    image: "https://picsum.photos/200?11",
  },
  {
    id: 12,
    title: "Refactoring",
    author: "Martin Fowler",
    status: "Indisponible",
    image: "https://picsum.photos/200?12",
  },
  {
    id: 13,
    title: "Algorithms",
    author: "Thomas Cormen",
    status: "Disponible",
    image: "https://picsum.photos/200?13",
  },
  {
    id: 14,
    title: "Data Structures",
    author: "Mark Allen Weiss",
    status: "Disponible",
    image: "https://picsum.photos/200?14",
  },
  {
    id: 15,
    title: "Git & GitHub",
    author: "Scott Chacon",
    status: "Disponible",
    image: "https://picsum.photos/200?15",
  },
  {
    id: 16,
    title: "Docker Basics",
    author: "Nigel Poulton",
    status: "Indisponible",
    image: "https://picsum.photos/200?16",
  },
  {
    id: 17,
    title: "DevOps Handbook",
    author: "Gene Kim",
    status: "Disponible",
    image: "https://picsum.photos/200?17",
  },
  {
    id: 18,
    title: "MongoDB Guide",
    author: "Kristina Chodorow",
    status: "Disponible",
    image: "https://picsum.photos/200?18",
  },
  {
    id: 19,
    title: "SQL Mastery",
    author: "Alan Beaulieu",
    status: "Disponible",
    image: "https://picsum.photos/200?19",
  },
  {
    id: 20,
    title: "AI Basics",
    author: "Andrew Ng",
    status: "Indisponible",
    image: "https://picsum.photos/200?20",
  },
  {
    id: 21,
    title: "Machine Learning",
    author: "Tom Mitchell",
    status: "Disponible",
    image: "https://picsum.photos/200?21",
  }
  
];

export default books;